### ISSUE TITLE
[Add Algorithm]: Add the code for Binary Search

### ISSUE THREAD

**Issue by ketan-sonar** [pccoe-acm-hacktoberfest-2023/Data-Structures-and-Algorithms#1]
# Description

- Add the code for Binary Search written in C.  
- Follow all the guidelines given in the CONTRIBUTING.md file.

**Comment by Varadpatil21** [comment]
@ketan-sonar I want to contribute on given issue. Please assign me the issue

**Comment by Girish345** [comment]
I want to work on that can you please assign it to me

**Comment by AryaKale16** [comment]
Hey @ketan-sonar,
I would like to address this issue, I will also be adding details about binary search with steps.
kindly consider assigning me this issue...
my portfolio website:  [Link](http://aryakale.me/)
