### ISSUE TITLE
[Add Algorithm]: Add Bubble Sort Algorithm

### ISSUE THREAD

**Issue by ketan-sonar** [pccoe-acm-hacktoberfest-2023/Data-Structures-and-Algorithms#2]
# Description
- Make a separate folder for Sorting Algorithms First
- Add the code for Bubble Sort Algorithm written in C.
- Follow the guidelines given in the CONTRIBUTING.md file

**Comment by Girish345** [comment]
I want to work on that can you please assign it to me

**Comment by pranav-lad** [comment]
Hey ketan, I would like to contribute to this issue and will do that by adding all the necessary details about bubble sort...
here's my profile https://linktr.ee/pranavlad 
hoping it will convince you...

**Comment by pccoe-acm** [comment]
@pranav-lad  i have assigned it to you  do it  and follow the description as well before making a PR
